set -u
cd "mnt/RainonUI/Media/Sounds" || { echo "NO DIR"; exit 1; }
mkdir -p "../../_to_delete/Sounds_old"
renamed=0; skipped=0
if [ -f "0 Absorb - Alice by Rainon.ogg" ]; then mv -n -- "0 Absorb - Alice by Rainon.ogg" "RainonUI_Absorb.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Absorb.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Absorb - Alice by Rainon.ogg"; fi
if [ -f "0 Adds - Alice by Rainon.ogg" ]; then mv -n -- "0 Adds - Alice by Rainon.ogg" "RainonUI_Adds.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Adds.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Adds - Alice by Rainon.ogg"; fi
if [ -f "0 Adds Summon - Alice by Rainon.ogg" ]; then mv -n -- "0 Adds Summon - Alice by Rainon.ogg" "RainonUI_Adds_Summon.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Adds_Summon.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Adds Summon - Alice by Rainon.ogg"; fi
if [ -f "0 Agro - Alice by Rainon.ogg" ]; then mv -n -- "0 Agro - Alice by Rainon.ogg" "RainonUI_Agro.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Agro.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Agro - Alice by Rainon.ogg"; fi
if [ -f "0 All ready - Alice by Rainon.ogg" ]; then mv -n -- "0 All ready - Alice by Rainon.ogg" "RainonUI_All_ready.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_All_ready.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 All ready - Alice by Rainon.ogg"; fi
if [ -f "0 Ancestral Guidance - Alice by Rainon.ogg" ]; then mv -n -- "0 Ancestral Guidance - Alice by Rainon.ogg" "RainonUI_Ancestral_Guidance.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Ancestral_Guidance.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Ancestral Guidance - Alice by Rainon.ogg"; fi
if [ -f "0 Anti Magic Zone - Alice by Rainon.ogg" ]; then mv -n -- "0 Anti Magic Zone - Alice by Rainon.ogg" "RainonUI_Anti_Magic_Zone.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Anti_Magic_Zone.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Anti Magic Zone - Alice by Rainon.ogg"; fi
if [ -f "0 Anti Magic Zone Eng - Alice by Rainon.ogg" ]; then mv -n -- "0 Anti Magic Zone Eng - Alice by Rainon.ogg" "RainonUI_Anti_Magic_Zone_Eng.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Anti_Magic_Zone_Eng.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Anti Magic Zone Eng - Alice by Rainon.ogg"; fi
if [ -f "0 AoE - Alice by Rainon.ogg" ]; then mv -n -- "0 AoE - Alice by Rainon.ogg" "RainonUI_AoE.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_AoE.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 AoE - Alice by Rainon.ogg"; fi
if [ -f "0 Attention - Alice by Rainon.ogg" ]; then mv -n -- "0 Attention - Alice by Rainon.ogg" "RainonUI_Attention.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Attention.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Attention - Alice by Rainon.ogg"; fi
if [ -f "0 Aura Mastery - Alice by Rainon.ogg" ]; then mv -n -- "0 Aura Mastery - Alice by Rainon.ogg" "RainonUI_Aura_Mastery.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Aura_Mastery.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Aura Mastery - Alice by Rainon.ogg"; fi
if [ -f "0 Barrel - Alice by Rainon.ogg" ]; then mv -n -- "0 Barrel - Alice by Rainon.ogg" "RainonUI_Barrel.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Barrel.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Barrel - Alice by Rainon.ogg"; fi
if [ -f "0 Barrier - Alice by Rainon.ogg" ]; then mv -n -- "0 Barrier - Alice by Rainon.ogg" "RainonUI_Barrier.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Barrier.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Barrier - Alice by Rainon.ogg"; fi
if [ -f "0 Beam - Alice by Rainon.ogg" ]; then mv -n -- "0 Beam - Alice by Rainon.ogg" "RainonUI_Beam.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Beam.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Beam - Alice by Rainon.ogg"; fi
if [ -f "0 Beam Phase - Alice by Rainon.ogg" ]; then mv -n -- "0 Beam Phase - Alice by Rainon.ogg" "RainonUI_Beam_Phase.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Beam_Phase.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Beam Phase - Alice by Rainon.ogg"; fi
if [ -f "0 Berserk - Alice by Rainon.ogg" ]; then mv -n -- "0 Berserk - Alice by Rainon.ogg" "RainonUI_Berserk.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Berserk.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Berserk - Alice by Rainon.ogg"; fi
if [ -f "0 Blessing of Freedom - Alice by Rainon.ogg" ]; then mv -n -- "0 Blessing of Freedom - Alice by Rainon.ogg" "RainonUI_Blessing_of_Freedom.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Blessing_of_Freedom.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Blessing of Freedom - Alice by Rainon.ogg"; fi
if [ -f "0 Blessing of Protection - Alice by Rainon.ogg" ]; then mv -n -- "0 Blessing of Protection - Alice by Rainon.ogg" "RainonUI_Blessing_of_Protection.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Blessing_of_Protection.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Blessing of Protection - Alice by Rainon.ogg"; fi
if [ -f "0 Blessing of Sacrifice - Alice by Rainon.ogg" ]; then mv -n -- "0 Blessing of Sacrifice - Alice by Rainon.ogg" "RainonUI_Blessing_of_Sacrifice.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Blessing_of_Sacrifice.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Blessing of Sacrifice - Alice by Rainon.ogg"; fi
if [ -f "0 Blue - Overlord by Rainon.ogg" ]; then mv -n -- "0 Blue - Overlord by Rainon.ogg" "RainonUI_Blue.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Blue.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Blue - Overlord by Rainon.ogg"; fi
if [ -f "0 Boiler - Alice by Rainon.ogg" ]; then mv -n -- "0 Boiler - Alice by Rainon.ogg" "RainonUI_Boiler.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Boiler.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Boiler - Alice by Rainon.ogg"; fi
if [ -f "0 Bombardment - Alice by Rainon.ogg" ]; then mv -n -- "0 Bombardment - Alice by Rainon.ogg" "RainonUI_Bombardment.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Bombardment.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Bombardment - Alice by Rainon.ogg"; fi
if [ -f "0 Bombs - Alice by Rainon.ogg" ]; then mv -n -- "0 Bombs - Alice by Rainon.ogg" "RainonUI_Bombs.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Bombs.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Bombs - Alice by Rainon.ogg"; fi
if [ -f "0 Boss - Alice by Rainon.ogg" ]; then mv -n -- "0 Boss - Alice by Rainon.ogg" "RainonUI_Boss.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Boss.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Boss - Alice by Rainon.ogg"; fi
if [ -f "0 Boss Feed - Alice by Rainon.ogg" ]; then mv -n -- "0 Boss Feed - Alice by Rainon.ogg" "RainonUI_Boss_Feed.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Boss_Feed.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Boss Feed - Alice by Rainon.ogg"; fi
if [ -f "0 Boss Vulnerable - Alice by Rainon.ogg" ]; then mv -n -- "0 Boss Vulnerable - Alice by Rainon.ogg" "RainonUI_Boss_Vulnerable.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Boss_Vulnerable.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Boss Vulnerable - Alice by Rainon.ogg"; fi
if [ -f "0 Breath - Alice by Rainon.ogg" ]; then mv -n -- "0 Breath - Alice by Rainon.ogg" "RainonUI_Breath.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Breath.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Breath - Alice by Rainon.ogg"; fi
if [ -f "0 Brown - Overlord by Rainon.ogg" ]; then mv -n -- "0 Brown - Overlord by Rainon.ogg" "RainonUI_Brown.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Brown.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Brown - Overlord by Rainon.ogg"; fi
if [ -f "0 Cast - Alice by Rainon.ogg" ]; then mv -n -- "0 Cast - Alice by Rainon.ogg" "RainonUI_Cast.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Cast.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Cast - Alice by Rainon.ogg"; fi
if [ -f "0 Cast - Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Cast - Kick - Alice by Rainon.ogg" "RainonUI_Cast_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Cast_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Cast - Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Cast - Kick Boss - Alice by Rainon.ogg" ]; then mv -n -- "0 Cast - Kick Boss - Alice by Rainon.ogg" "RainonUI_Cast_Kick_Boss.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Cast_Kick_Boss.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Cast - Kick Boss - Alice by Rainon.ogg"; fi
if [ -f "0 Cast CC - Alice by Rainon.ogg" ]; then mv -n -- "0 Cast CC - Alice by Rainon.ogg" "RainonUI_Cast_CC.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Cast_CC.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Cast CC - Alice by Rainon.ogg"; fi
if [ -f "0 Change Race - Alice by Rainon.ogg" ]; then mv -n -- "0 Change Race - Alice by Rainon.ogg" "RainonUI_Change_Race.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Change_Race.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Change Race - Alice by Rainon.ogg"; fi
if [ -f "0 Charge - Alice by Rainon.ogg" ]; then mv -n -- "0 Charge - Alice by Rainon.ogg" "RainonUI_Charge.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Charge.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Charge - Alice by Rainon.ogg"; fi
if [ -f "0 Cleave - Alice by Rainon.ogg" ]; then mv -n -- "0 Cleave - Alice by Rainon.ogg" "RainonUI_Cleave.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Cleave.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Cleave - Alice by Rainon.ogg"; fi
if [ -f "0 Come to Melee - Alice by Rainon.ogg" ]; then mv -n -- "0 Come to Melee - Alice by Rainon.ogg" "RainonUI_Come_to_Melee.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Come_to_Melee.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Come to Melee - Alice by Rainon.ogg"; fi
if [ -f "0 Come to the Boss - Alice by Rainon.ogg" ]; then mv -n -- "0 Come to the Boss - Alice by Rainon.ogg" "RainonUI_Come_to_the_Boss.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Come_to_the_Boss.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Come to the Boss - Alice by Rainon.ogg"; fi
if [ -f "0 Darkness - Alice by Rainon.ogg" ]; then mv -n -- "0 Darkness - Alice by Rainon.ogg" "RainonUI_Darkness.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Darkness.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Darkness - Alice by Rainon.ogg"; fi
if [ -f "0 Darkness Eng - Alice by Rainon.ogg" ]; then mv -n -- "0 Darkness Eng - Alice by Rainon.ogg" "RainonUI_Darkness_Eng.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Darkness_Eng.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Darkness Eng - Alice by Rainon.ogg"; fi
if [ -f "0 Debuff disappeared - Alice by Rainon.ogg" ]; then mv -n -- "0 Debuff disappeared - Alice by Rainon.ogg" "RainonUI_Debuff_disappeared.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Debuff_disappeared.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Debuff disappeared - Alice by Rainon.ogg"; fi
if [ -f "0 Dispell Yourself - Alice by Rainon.ogg" ]; then mv -n -- "0 Dispell Yourself - Alice by Rainon.ogg" "RainonUI_Dispell_Yourself.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Dispell_Yourself.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Dispell Yourself - Alice by Rainon.ogg"; fi
if [ -f "0 Dodge - Alice by Rainon.ogg" ]; then mv -n -- "0 Dodge - Alice by Rainon.ogg" "RainonUI_Dodge.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Dodge.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Dodge - Alice by Rainon.ogg"; fi
if [ -f "0 Drag the Spider - Alice by Rainon.ogg" ]; then mv -n -- "0 Drag the Spider - Alice by Rainon.ogg" "RainonUI_Drag_the_Spider.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Drag_the_Spider.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Drag the Spider - Alice by Rainon.ogg"; fi
if [ -f "0 Fear - Alice by Rainon.ogg" ]; then mv -n -- "0 Fear - Alice by Rainon.ogg" "RainonUI_Fear.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Fear.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Fear - Alice by Rainon.ogg"; fi
if [ -f "0 Fear Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Fear Kick - Alice by Rainon.ogg" "RainonUI_Fear_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Fear_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Fear Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Fixate on you - Alice by Rainon.ogg" ]; then mv -n -- "0 Fixate on you - Alice by Rainon.ogg" "RainonUI_Fixate_on_you.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Fixate_on_you.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Fixate on you - Alice by Rainon.ogg"; fi
if [ -f "0 Fly - Alice by Rainon.ogg" ]; then mv -n -- "0 Fly - Alice by Rainon.ogg" "RainonUI_Fly.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Fly.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Fly - Alice by Rainon.ogg"; fi
if [ -f "0 Food - Alice by Rainon.ogg" ]; then mv -n -- "0 Food - Alice by Rainon.ogg" "RainonUI_Food.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Food.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Food - Alice by Rainon.ogg"; fi
if [ -f "0 Food Hearty Well Fed - Alice by Rainon.ogg" ]; then mv -n -- "0 Food Hearty Well Fed - Alice by Rainon.ogg" "RainonUI_Food_Hearty_Well_Fed.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Food_Hearty_Well_Fed.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Food Hearty Well Fed - Alice by Rainon.ogg"; fi
if [ -f "0 Go out - Alice by Rainon.ogg" ]; then mv -n -- "0 Go out - Alice by Rainon.ogg" "RainonUI_Go_out.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Go_out.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Go out - Alice by Rainon.ogg"; fi
if [ -f "0 Go out from ppl - Alice by Rainon.ogg" ]; then mv -n -- "0 Go out from ppl - Alice by Rainon.ogg" "RainonUI_Go_out_from_ppl.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Go_out_from_ppl.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Go out from ppl - Alice by Rainon.ogg"; fi
if [ -f "0 Go to portal - Alice by Rainon.ogg" ]; then mv -n -- "0 Go to portal - Alice by Rainon.ogg" "RainonUI_Go_to_portal.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Go_to_portal.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Go to portal - Alice by Rainon.ogg"; fi
if [ -f "0 Green - Overlord by Rainon.ogg" ]; then mv -n -- "0 Green - Overlord by Rainon.ogg" "RainonUI_Green.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Green.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Green - Overlord by Rainon.ogg"; fi
if [ -f "0 Guardian Spirit - Alice by Rainon.ogg" ]; then mv -n -- "0 Guardian Spirit - Alice by Rainon.ogg" "RainonUI_Guardian_Spirit.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Guardian_Spirit.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Guardian Spirit - Alice by Rainon.ogg"; fi
if [ -f "0 Guessing Game - Alice by Rainon.ogg" ]; then mv -n -- "0 Guessing Game - Alice by Rainon.ogg" "RainonUI_Guessing_Game.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Guessing_Game.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Guessing Game - Alice by Rainon.ogg"; fi
if [ -f "0 Heal - Alice by Rainon.ogg" ]; then mv -n -- "0 Heal - Alice by Rainon.ogg" "RainonUI_Heal.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Heal.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Heal - Alice by Rainon.ogg"; fi
if [ -f "0 Heal Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Heal Kick - Alice by Rainon.ogg" "RainonUI_Heal_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Heal_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Heal Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Health Stones - Alice by Rainon.ogg" ]; then mv -n -- "0 Health Stones - Alice by Rainon.ogg" "RainonUI_Health_Stones.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Health_Stones.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Health Stones - Alice by Rainon.ogg"; fi
if [ -f "0 Heroism - Alice by Rainon.ogg" ]; then mv -n -- "0 Heroism - Alice by Rainon.ogg" "RainonUI_Heroism.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Heroism.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Heroism - Alice by Rainon.ogg"; fi
if [ -f "0 Hit - Alice by Rainon.ogg" ]; then mv -n -- "0 Hit - Alice by Rainon.ogg" "RainonUI_Hit.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Hit.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Hit - Alice by Rainon.ogg"; fi
if [ -f "0 Holy Bulwark - Alice by Rainon.ogg" ]; then mv -n -- "0 Holy Bulwark - Alice by Rainon.ogg" "RainonUI_Holy_Bulwark.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Holy_Bulwark.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Holy Bulwark - Alice by Rainon.ogg"; fi
if [ -f "0 Ice Barrier - Alice by Rainon.ogg" ]; then mv -n -- "0 Ice Barrier - Alice by Rainon.ogg" "RainonUI_Ice_Barrier.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Ice_Barrier.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Ice Barrier - Alice by Rainon.ogg"; fi
if [ -f "0 Ironbark - Alice by Rainon.ogg" ]; then mv -n -- "0 Ironbark - Alice by Rainon.ogg" "RainonUI_Ironbark.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Ironbark.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Ironbark - Alice by Rainon.ogg"; fi
if [ -f "0 Kick Arrows - Alice by Rainon.ogg" ]; then mv -n -- "0 Kick Arrows - Alice by Rainon.ogg" "RainonUI_Kick_Arrows.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Kick_Arrows.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Kick Arrows - Alice by Rainon.ogg"; fi
if [ -f "0 Kick CC - Alice by Rainon.ogg" ]; then mv -n -- "0 Kick CC - Alice by Rainon.ogg" "RainonUI_Kick_CC.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Kick_CC.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Kick CC - Alice by Rainon.ogg"; fi
if [ -f "0 Lead group - Alice by Rainon.ogg" ]; then mv -n -- "0 Lead group - Alice by Rainon.ogg" "RainonUI_Lead_group.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Lead_group.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Lead group - Alice by Rainon.ogg"; fi
if [ -f "0 Life Cocoon - Alice by Rainon.ogg" ]; then mv -n -- "0 Life Cocoon - Alice by Rainon.ogg" "RainonUI_Life_Cocoon.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Life_Cocoon.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Life Cocoon - Alice by Rainon.ogg"; fi
if [ -f "0 Mage table - Alice by Rainon.ogg" ]; then mv -n -- "0 Mage table - Alice by Rainon.ogg" "RainonUI_Mage_table.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Mage_table.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Mage table - Alice by Rainon.ogg"; fi
if [ -f "0 Mail Box - Alice by Rainon.ogg" ]; then mv -n -- "0 Mail Box - Alice by Rainon.ogg" "RainonUI_Mail_Box.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Mail_Box.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Mail Box - Alice by Rainon.ogg"; fi
if [ -f "0 Mana - Alice by Rainon.ogg" ]; then mv -n -- "0 Mana - Alice by Rainon.ogg" "RainonUI_Mana.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Mana.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Mana - Alice by Rainon.ogg"; fi
if [ -f "0 Mass Invisibility - Alice by Rainon.ogg" ]; then mv -n -- "0 Mass Invisibility - Alice by Rainon.ogg" "RainonUI_Mass_Invisibility.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Mass_Invisibility.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Mass Invisibility - Alice by Rainon.ogg"; fi
if [ -f "0 Misdirection - Alice by Rainon.ogg" ]; then mv -n -- "0 Misdirection - Alice by Rainon.ogg" "RainonUI_Misdirection.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Misdirection.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Misdirection - Alice by Rainon.ogg"; fi
if [ -f "0 Pain Suppression - Alice by Rainon.ogg" ]; then mv -n -- "0 Pain Suppression - Alice by Rainon.ogg" "RainonUI_Pain_Suppression.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Pain_Suppression.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Pain Suppression - Alice by Rainon.ogg"; fi
if [ -f "0 Pass it on Debuff - Alice by Rainon.ogg" ]; then mv -n -- "0 Pass it on Debuff - Alice by Rainon.ogg" "RainonUI_Pass_it_on_Debuff.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Pass_it_on_Debuff.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Pass it on Debuff - Alice by Rainon.ogg"; fi
if [ -f "0 Patty Cake - Alice by Rainon.ogg" ]; then mv -n -- "0 Patty Cake - Alice by Rainon.ogg" "RainonUI_Patty_Cake.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Patty_Cake.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Patty Cake - Alice by Rainon.ogg"; fi
if [ -f "0 Phase change - Alice by Rainon.ogg" ]; then mv -n -- "0 Phase change - Alice by Rainon.ogg" "RainonUI_Phase_change.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Phase_change.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Phase change - Alice by Rainon.ogg"; fi
if [ -f "0 Poison Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Poison Kick - Alice by Rainon.ogg" "RainonUI_Poison_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Poison_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Poison Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Potion - Alice by Rainon.ogg" ]; then mv -n -- "0 Potion - Alice by Rainon.ogg" "RainonUI_Potion.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Potion.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Potion - Alice by Rainon.ogg"; fi
if [ -f "0 Push - Alice by Rainon.ogg" ]; then mv -n -- "0 Push - Alice by Rainon.ogg" "RainonUI_Push.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Push.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Push - Alice by Rainon.ogg"; fi
if [ -f "0 Putin - by Rainon.ogg" ]; then mv -n -- "0 Putin - by Rainon.ogg" "RainonUI_Putin.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Putin.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Putin - by Rainon.ogg"; fi
if [ -f "0 Rallying Cry - Alice by Rainon.ogg" ]; then mv -n -- "0 Rallying Cry - Alice by Rainon.ogg" "RainonUI_Rallying_Cry.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Rallying_Cry.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Rallying Cry - Alice by Rainon.ogg"; fi
if [ -f "0 Red - Overlord by Rainon.ogg" ]; then mv -n -- "0 Red - Overlord by Rainon.ogg" "RainonUI_Red.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Red.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Red - Overlord by Rainon.ogg"; fi
if [ -f "0 Repair - Alice by Rainon.ogg" ]; then mv -n -- "0 Repair - Alice by Rainon.ogg" "RainonUI_Repair.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Repair.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Repair - Alice by Rainon.ogg"; fi
if [ -f "0 Rewind - Alice by Rainon.ogg" ]; then mv -n -- "0 Rewind - Alice by Rainon.ogg" "RainonUI_Rewind.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Rewind.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Rewind - Alice by Rainon.ogg"; fi
if [ -f "0 Ritual of Summoning - Alice by Rainon.ogg" ]; then mv -n -- "0 Ritual of Summoning - Alice by Rainon.ogg" "RainonUI_Ritual_of_Summoning.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Ritual_of_Summoning.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Ritual of Summoning - Alice by Rainon.ogg"; fi
if [ -f "0 Run away - Alice by Rainon.ogg" ]; then mv -n -- "0 Run away - Alice by Rainon.ogg" "RainonUI_Run_away.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Run_away.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Run away - Alice by Rainon.ogg"; fi
if [ -f "0 Runaways - Alice by Rainon.ogg" ]; then mv -n -- "0 Runaways - Alice by Rainon.ogg" "RainonUI_Runaways.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Runaways.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Runaways - Alice by Rainon.ogg"; fi
if [ -f "0 Save Kaktys - Alice by Rainon.ogg" ]; then mv -n -- "0 Save Kaktys - Alice by Rainon.ogg" "RainonUI_Save_Kaktys.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Save_Kaktys.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Save Kaktys - Alice by Rainon.ogg"; fi
if [ -f "0 Scream - Alice by Rainon.ogg" ]; then mv -n -- "0 Scream - Alice by Rainon.ogg" "RainonUI_Scream.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Scream.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Scream - Alice by Rainon.ogg"; fi
if [ -f "0 Scream Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Scream Kick - Alice by Rainon.ogg" "RainonUI_Scream_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Scream_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Scream Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Share - Alice by Rainon.ogg" ]; then mv -n -- "0 Share - Alice by Rainon.ogg" "RainonUI_Share.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Share.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Share - Alice by Rainon.ogg"; fi
if [ -f "0 Share Debuff - Alice by Rainon.ogg" ]; then mv -n -- "0 Share Debuff - Alice by Rainon.ogg" "RainonUI_Share_Debuff.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Share_Debuff.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Share Debuff - Alice by Rainon.ogg"; fi
if [ -f "0 Shield - Alice by Rainon.ogg" ]; then mv -n -- "0 Shield - Alice by Rainon.ogg" "RainonUI_Shield.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Shield.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Shield - Alice by Rainon.ogg"; fi
if [ -f "0 Shield Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Shield Kick - Alice by Rainon.ogg" "RainonUI_Shield_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Shield_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Shield Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Shoot - Alice by Rainon.ogg" ]; then mv -n -- "0 Shoot - Alice by Rainon.ogg" "RainonUI_Shoot.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Shoot.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Shoot - Alice by Rainon.ogg"; fi
if [ -f "0 Shroud - Alice by Rainon.ogg" ]; then mv -n -- "0 Shroud - Alice by Rainon.ogg" "RainonUI_Shroud.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Shroud.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Shroud - Alice by Rainon.ogg"; fi
if [ -f "0 Silence - Alice by Rainon.ogg" ]; then mv -n -- "0 Silence - Alice by Rainon.ogg" "RainonUI_Silence.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Silence.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Silence - Alice by Rainon.ogg"; fi
if [ -f "0 Silence Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Silence Kick - Alice by Rainon.ogg" "RainonUI_Silence_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Silence_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Silence Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Spirit Link Totem - Alice by Rainon.ogg" ]; then mv -n -- "0 Spirit Link Totem - Alice by Rainon.ogg" "RainonUI_Spirit_Link_Totem.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Spirit_Link_Totem.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Spirit Link Totem - Alice by Rainon.ogg"; fi
if [ -f "0 Spirit Link Totem Eng - Alice by Rainon.ogg" ]; then mv -n -- "0 Spirit Link Totem Eng - Alice by Rainon.ogg" "RainonUI_Spirit_Link_Totem_Eng.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Spirit_Link_Totem_Eng.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Spirit Link Totem Eng - Alice by Rainon.ogg"; fi
if [ -f "0 Spread - Alice by Rainon.ogg" ]; then mv -n -- "0 Spread - Alice by Rainon.ogg" "RainonUI_Spread.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Spread.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Spread - Alice by Rainon.ogg"; fi
if [ -f "0 Stacks - Alice by Rainon.ogg" ]; then mv -n -- "0 Stacks - Alice by Rainon.ogg" "RainonUI_Stacks.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Stacks.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Stacks - Alice by Rainon.ogg"; fi
if [ -f "0 Stoneskin Totem - Alice by Rainon.ogg" ]; then mv -n -- "0 Stoneskin Totem - Alice by Rainon.ogg" "RainonUI_Stoneskin_Totem.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Stoneskin_Totem.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Stoneskin Totem - Alice by Rainon.ogg"; fi
if [ -f "0 Stop soak - Alice by Rainon.ogg" ]; then mv -n -- "0 Stop soak - Alice by Rainon.ogg" "RainonUI_Stop_soak.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Stop_soak.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Stop soak - Alice by Rainon.ogg"; fi
if [ -f "0 Stun - Alice by Rainon.ogg" ]; then mv -n -- "0 Stun - Alice by Rainon.ogg" "RainonUI_Stun.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Stun.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Stun - Alice by Rainon.ogg"; fi
if [ -f "0 Stun Kick - Alice by Rainon.ogg" ]; then mv -n -- "0 Stun Kick - Alice by Rainon.ogg" "RainonUI_Stun_Kick.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Stun_Kick.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Stun Kick - Alice by Rainon.ogg"; fi
if [ -f "0 Summon - Alice by Rainon.ogg" ]; then mv -n -- "0 Summon - Alice by Rainon.ogg" "RainonUI_Summon.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Summon.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Summon - Alice by Rainon.ogg"; fi
if [ -f "0 Tank Combo - Alice by Rainon.ogg" ]; then mv -n -- "0 Tank Combo - Alice by Rainon.ogg" "RainonUI_Tank_Combo.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Tank_Combo.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Tank Combo - Alice by Rainon.ogg"; fi
if [ -f "0 Tank Switch - Alice by Rainon.ogg" ]; then mv -n -- "0 Tank Switch - Alice by Rainon.ogg" "RainonUI_Tank_Switch.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Tank_Switch.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Tank Switch - Alice by Rainon.ogg"; fi
if [ -f "0 Taunt - Alice by Rainon.ogg" ]; then mv -n -- "0 Taunt - Alice by Rainon.ogg" "RainonUI_Taunt.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Taunt.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Taunt - Alice by Rainon.ogg"; fi
if [ -f "0 Taunt push - Alice by Rainon.ogg" ]; then mv -n -- "0 Taunt push - Alice by Rainon.ogg" "RainonUI_Taunt_push.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Taunt_push.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Taunt push - Alice by Rainon.ogg"; fi
if [ -f "0 Time Dilation - Alice by Rainon.ogg" ]; then mv -n -- "0 Time Dilation - Alice by Rainon.ogg" "RainonUI_Time_Dilation.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Time_Dilation.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Time Dilation - Alice by Rainon.ogg"; fi
if [ -f "0 Totem - Alice by Rainon.ogg" ]; then mv -n -- "0 Totem - Alice by Rainon.ogg" "RainonUI_Totem.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Totem.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Totem - Alice by Rainon.ogg"; fi
if [ -f "0 TWW Phase Blades - Alice by Rainon.ogg" ]; then mv -n -- "0 TWW Phase Blades - Alice by Rainon.ogg" "RainonUI_TWW_Phase_Blades.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_TWW_Phase_Blades.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 TWW Phase Blades - Alice by Rainon.ogg"; fi
if [ -f "0 Vampiric Embrace - Alice by Rainon.ogg" ]; then mv -n -- "0 Vampiric Embrace - Alice by Rainon.ogg" "RainonUI_Vampiric_Embrace.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Vampiric_Embrace.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Vampiric Embrace - Alice by Rainon.ogg"; fi
if [ -f "0 Wave - Alice by Rainon.ogg" ]; then mv -n -- "0 Wave - Alice by Rainon.ogg" "RainonUI_Wave.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Wave.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Wave - Alice by Rainon.ogg"; fi
if [ -f "0 Zephyr - Alice by Rainon.ogg" ]; then mv -n -- "0 Zephyr - Alice by Rainon.ogg" "RainonUI_Zephyr.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Zephyr.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Zephyr - Alice by Rainon.ogg"; fi
if [ -f "0 Zephyr Eng - Alice by Rainon.ogg" ]; then mv -n -- "0 Zephyr Eng - Alice by Rainon.ogg" "RainonUI_Zephyr_Eng.ogg" && renamed=$((renamed+1)); elif [ -f "RainonUI_Zephyr_Eng.ogg" ]; then skipped=$((skipped+1)); else echo "MISS: 0 Zephyr Eng - Alice by Rainon.ogg"; fi
echo "renamed=$renamed already=$skipped"
# --- чистка байт-идентичных старых дублей ---
if [ -f "allready.ogg" ]; then if cmp -s "allready.ogg" "RainonUI_All_ready.ogg"; then mv -- "allready.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: allready.ogg"; else echo "DIFF (kept): allready.ogg"; fi; fi
if [ -f "cauldron.ogg" ]; then if cmp -s "cauldron.ogg" "RainonUI_Boiler.ogg"; then mv -- "cauldron.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: cauldron.ogg"; else echo "DIFF (kept): cauldron.ogg"; fi; fi
if [ -f "feast.ogg" ]; then if cmp -s "feast.ogg" "RainonUI_Food_Hearty_Well_Fed.ogg"; then mv -- "feast.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: feast.ogg"; else echo "DIFF (kept): feast.ogg"; fi; fi
if [ -f "food.ogg" ]; then if cmp -s "food.ogg" "RainonUI_Food.ogg"; then mv -- "food.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: food.ogg"; else echo "DIFF (kept): food.ogg"; fi; fi
if [ -f "healthstones.ogg" ]; then if cmp -s "healthstones.ogg" "RainonUI_Health_Stones.ogg"; then mv -- "healthstones.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: healthstones.ogg"; else echo "DIFF (kept): healthstones.ogg"; fi; fi
if [ -f "leader.ogg" ]; then if cmp -s "leader.ogg" "RainonUI_Lead_group.ogg"; then mv -- "leader.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: leader.ogg"; else echo "DIFF (kept): leader.ogg"; fi; fi
if [ -f "magetable.ogg" ]; then if cmp -s "magetable.ogg" "RainonUI_Mage_table.ogg"; then mv -- "magetable.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: magetable.ogg"; else echo "DIFF (kept): magetable.ogg"; fi; fi
if [ -f "mail.ogg" ]; then if cmp -s "mail.ogg" "RainonUI_Mail_Box.ogg"; then mv -- "mail.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: mail.ogg"; else echo "DIFF (kept): mail.ogg"; fi; fi
if [ -f "racechange.ogg" ]; then if cmp -s "racechange.ogg" "RainonUI_Change_Race.ogg"; then mv -- "racechange.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: racechange.ogg"; else echo "DIFF (kept): racechange.ogg"; fi; fi
if [ -f "repair.ogg" ]; then if cmp -s "repair.ogg" "RainonUI_Repair.ogg"; then mv -- "repair.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: repair.ogg"; else echo "DIFF (kept): repair.ogg"; fi; fi
if [ -f "summon.ogg" ]; then if cmp -s "summon.ogg" "RainonUI_Ritual_of_Summoning.ogg"; then mv -- "summon.ogg" "../../_to_delete/Sounds_old/" && echo "DUP moved: summon.ogg"; else echo "DIFF (kept): summon.ogg"; fi; fi
echo "=== final count in Sounds ==="; ls | wc -l
